service: serverless-python

provider:
  name: aws
  runtime: python3.6
  timeout: 30
  stage: dev
  region: ap-northeast-1



functions:
  hello:
    handler: handler.hello

    events:
      - http:
          path: users/demo
          method: post
          cors: true
